### ISSUE TITLE
Godot implementation

### ISSUE THREAD

**Issue by drsounds** [vanjac/voxel-editor#365]
I know this isnt a simple thing but I would like to see if the author or someone else are interested in forking this project and porting it to Godot Engine and replace the Standard Unity Assets with public domain assets from Godot AssetLib.
I am a little afraid this project might be a grey zone legally since it uses a commercial paid proprierty engine and its Standard Assets. I am afraid it could be a violation of the asset license to redistribute them in an open source project like this.

**Comment by vanjac** [comment]
I'd love to see a Godot version of N-Space or something like it, but I don't have the time/interest to work on that myself.

I'm not personally concerned the use of standard assets here. They are very widespread and Unity seems to allow their usage/redistribution, at least based on their [FAQ](https://unity.com/faq). I'm only using a handful of scripts/shaders/models from the standard assets, so they could be individually replaced if needed without starting from scratch.
