### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by vanjac** [vanjac/voxel-editor#378]
Objects with a mesh, selectable from either an asset bundle (#376) or a custom imported mesh (#217)

Collision is the convex hull of the mesh

Built-in meshes:
- Trees
-

**Comment by vanjac** [comment]
https://assetstore.unity.com/packages/3d/props/exterior/polygon-prototype-low-poly-3d-art-by-synty-137126

**Comment by vanjac** [comment]
@TaiTaiTai777 Can I ask why you're doing this? What do you get from posting these spam comments everywhere?

**Comment by TaiTaiTai777** [comment]
You can't do like me... Read more kid...

**Comment by vanjac** [comment]
Replacement for #255
